barang/urls.py
from django.urls import path
from . import views
app_name = 'barang'

urlpatterns = [
    path('listBarang/', views.readBarang, name ='readBarang'),
    path('createBarang/', views.createBarang, name = 'createBarang'),
    path('updateBarang/<int:pk>', views.updateBarang, name = 'updateBarang'),
    path('detailBarang/<int:pk>/', views.detailBarang, name = 'detailBarang'),
    path('deleteBarang/', views.deleteBarang, name = 'deleteBarang'),
]

thrift_shop/urls.py
from django.contrib import admin
from django.urls import include, path, re_path
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('authentication.urls')),
    path('barang/', include('barang.urls')),
    path('transaksi/', include('transaksi.urls')),
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

barang/models.py
from django.db import models
from django.conf import settings
from authentication.models import User
# Create your models here.

class Barang(models.Model):
    penjual = models.ForeignKey(User, on_delete= models.CASCADE, null = True)
    namaBarang = models.CharField(blank = False, max_length=30)
    idBarang = models.CharField(blank = False, max_length=30, unique=True)
    jenisBarang = models.CharField(blank = False, max_length=30)
    harga = models.IntegerField(blank=False)
    status = models.CharField(blank = False, max_length=30)
    ukuran = models.CharField(blank = False, max_length=30)
    kondisi = models.CharField(blank = False, max_length=30)
    is_terjual = models.BooleanField('Is Terjual', default = False)
    pembeli = models.CharField(null=True, max_length=30)
    def __str__(self):
        return self.idBarang

barang/forms.py
from django import forms
from django.forms import fields
from .models import Barang

class FormBarang(forms.ModelForm):
    idBarang = forms.CharField(
        required=True,
        widget= forms.TextInput(
            attrs={
                "class": "form-control"
            }
        )
    )
    namaBarang = forms.CharField(
        required=True,
        widget= forms.TextInput(
            attrs={
                "class": "form-control"
            }
        )
    )
    jenisBarang = forms.CharField(
        required=True,
        widget= forms.TextInput(
            attrs={
                "class": "form-control"
            }
        )
    )
    harga = forms.IntegerField(
        required=True,
        widget= forms.TextInput(
            attrs={
                "class": "form-control"
            }
        )
    )
    status = forms.CharField(
        required=True,
        widget= forms.TextInput(
            attrs={
                "class": "form-control"
            }
        )
    )
    ukuran = forms.CharField(
        required=True,
        widget= forms.TextInput(
            attrs={
                "class": "form-control"
            }
        )
    )
    kondisi = forms.CharField(
        required=True,
        widget= forms.TextInput(
            attrs={
                "class": "form-control"
            }
        )
    )

    class Meta:
        model = Barang
        fields = ('idBarang', 'namaBarang', 'jenisBarang', 'harga', 'status', 'ukuran', 'kondisi', 'is_terjual', 'pembeli')
    def __init__(self, *args, **kwargs):
        super(FormBarang, self).__init__(*args, **kwargs)
        self.fields['idBarang'].disabled = True

class BaseForm(forms.Form):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = 'form-control'

class UpdateForm(BaseForm, forms.ModelForm):
    class Meta:
        model = Barang
        fields = ('idBarang', 'namaBarang', 'jenisBarang', 'harga', 'status', 'ukuran', 'kondisi', 'is_terjual', 'pembeli')
    def __init__(self, *args, **kwargs):
        super(UpdateForm, self).__init__(*args, **kwargs)
        self.fields['idBarang'].disabled = True

barang/views.py
from django.shortcuts import render, redirect
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from .forms import FormBarang, UpdateForm
from django.conf import settings
from .models import Barang

# Create your views here.
def createBarang(request):
    if request.user.is_authenticated:
        msg = None
        form = FormBarang(request.POST or None)
        if Barang.objects.all().last() is None:
            id = 1
        else:
            val = Barang.objects.all().last()
            id = int(val.idBarang) + 1
        form.initial['idBarang'] = id
        if request.method == 'POST':
            if form.is_valid:
                try:
                    temp = Barang()
                    temp.namaBarang = request.POST['namaBarang']
                    tempPen = request.user
                    temp.penjual = tempPen
                    temp.idBarang = id
                    temp.jenisBarang = request.POST['jenisBarang']
                    temp.harga = request.POST['harga']
                    temp.status = request.POST['status']
                    temp.ukuran = request.POST['ukuran']
                    temp.kondisi = request.POST['kondisi']
                    temp.save()
                    msg = 'Barang berhasil dijual!'
                    return redirect('/barang/listBarang')
                except:
                    msg = 'Gagal'
                    return render(request, 'createBarang.html', {'form' : form, 'msg':msg})
            else:
                msg = 'Data kurang lengkap atau salah!'
        return render(request, 'createBarang.html', {'form' : form, 'msg':msg})
    else:
        return redirect('/')

def readBarang(request):
    if request.user.is_authenticated:
        listB = Barang.objects.all()
        p = request.user
        listBarang = Barang.objects.filter(penjual = p)
        return render(request, 'readBarang.html',{'listBarang' : listBarang, 'listB' : listB})
    else:
        return redirect('/')

def updateBarang(request, pk):
    if request.user.is_authenticated:
        msg = None
        hasil = Barang.objects.filter(idBarang = pk).first()
        #print(barangs)
        form = UpdateForm(instance = hasil)
        # form.initial['idBarang'] = hasil[0].idBarang
        # form.initial['namaBarang'] = hasil[0].namaBarang
        # form.initial['jenisBarang'] = hasil[0].jenisBarang
        # form.initial['harga'] = hasil[0].harga
        # form.initial['status'] = hasil[0].status
        # form.initial['ukuran'] = hasil[0].ukuran
        # form.initial['kondisi'] = hasil[0].kondisi
        if(request.method == 'POST' and form.is_valid):
            form = UpdateForm(request.POST, instance = hasil)
            form.save()
            return redirect('/barang/detailBarang/'+ str(pk))
        else:
            msg = 'Gagal!'
        return render(request, 'updateBarang.html', {'form' : form})
    else:
        return redirect('/')

def detailBarang(request, pk):
    if request.user.is_authenticated:
        detail = Barang.objects.filter(idBarang = pk).first()
        return render(request, 'detailBarang.html', {'detail' : detail})
    else:
        return redirect('/')

def deleteBarang(request):
    if request.user.is_authenticated:
        if request.method == 'GET':
            if request.GET.get('idBarang') is not None:
                Barang.objects.filter(idBarang = request.GET.get('idBarang')).delete()
        # listB = Barang.objects.all()
        # p = request.user
        # listBarang = Barang.objects.filter(penjual = p)
        return redirect('/barang/listBarang')
    else:
        return redirect('/')

barang/templates/createBarang.html
{% extends 'base.html' %}
{% block content %}

<h3 style="text-align: center;">MENDAFTARKAN BARANG BARU</h3>
<br>

<div class="d-flex justify-content-center">

    <form method="post">
        {% if msg %}
                {{ msg | safe }}
            {% endif %}
        {% csrf_token %}
        <div class="form-group">
            <label for="formGroupExampleInput">ID Barang:</label>
            {{form.idBarang}}
          </div>
        <div class="form-group">
            <label for="formGroupExampleInput">Nama Barang:</label>
            {{form.namaBarang}}
          </div>
          <div class="form-group">
            <label for="formGroupExampleInput">Jenis Barang:</label>
            {{form.jenisBarang}}
          </div>
          <div class="form-group">
            <label for="formGroupExampleInput">Harga:</label>
            {{form.harga}}
          </div>
        <div class="form-group">
            <label for="formGroupExampleInput">Status:</label>
            {{form.status}}
        </div>
        <div class="form-group">
            <label for="formGroupExampleInput">Ukuran:</label>
            {{form.ukuran}}
        </div>
        <div class="form-group">
            <label for="formGroupExampleInput">Kondisi:</label>
            {{form.kondisi}}
        </div>
          <span class="text-error">{{ form.errors }}</span>
        <div class="d-flex justify-content-center">
            <input type="submit"  value="Buat" class="btn btn-pill text-white btn-block btn-primary">
            <a class = "btn btn-danger" href="/barang/listBarang/">Batal</a>
        </div>
    </form>
</div>

{% endblock content %}

barang/templates/detailBarang.html
{% extends 'base.html' %}
{% block content %}

<h3>Detail Barang</h3>
<p>ID Barang: {{detail.idBarang}}</p>
<p>Nama Barang: {{detail.namaBarang}}</p>
<p>Jenis Barang: {{detail.jenisBarang}}</p>
<p>Harga Barang: {{detail.harga}}</p>
<p>Status Barang: {{detail.status}}</p>
<p>Ukuran Barang: {{detail.ukuran}}</p>
<p>Kondisi Barang: {{detail.kondisi}}</p>
<p>Pembeli: {{detail.pembeli}}</p>
<div class="d-flex justify-content-center">
    <a class = "btn btn-danger" href="/barang/listBarang/">Back</a>
</div>
{% endblock content %}

barang/templates/readBarang.html
{% extends 'base.html' %}
{% block content %}
<div class="d-flex justify-content-center">
    <h1 style="font-weight: bold;">List Barang</h1>
</div>
<br>
<div style="max-width:80%; margin-left: auto; margin-right: auto;">
    <table class="table table-hover">
        <thead>
          <tr style="text-align: center;">
            <th scope="col">ID Barang</th>
            <th scope="col">Nama Barang</th>
            <th scope="col">Harga</th>
            <th scope="col">Status</th>
            <th scope="col">Action</th>
          </tr>
        </thead>
        <tbody>
            {% if request.user.is_penjual == True%}
            {% for i in listBarang %}
            <tr style="text-align: center;">
                <th scope="row">{{i.idBarang}}</th>
                <td>{{i.namaBarang}}</td>
                <td>{{i.harga}}</td>
                <td>{{i.status}}</td>
                <td><div class="d-flex justify-content-center">
                {% if i.is_terjual == False %} 
                <button type="submit" class="btn btn-success"><a href="{% url 'barang:updateBarang' i.idBarang %}"
                style="text-decoration: none; color: #FFFFFF;">Update</a></button>
                {% endif %}
                <button class="btn btn-success"><a href="{% url 'barang:detailBarang' i.idBarang %}"
                  style="text-decoration: none; color: #FFFFFF;">Detail</a></button>
                
                <form action = "/barang/deleteBarang/" method ="get">
                    <input type = "hidden" id="idBarang" name="idBarang" value="{{i.idBarang}}">
                    <button type="submit" class="btn btn-danger">Delete</button>
                </form>

            </div></td> 
          </tr>
          {% endfor %}
          {% endif %}
          {% if request.user.is_pembeli == True %}
            {% for i in listB %}
            <tr style="text-align: center;">
                <th scope="row">{{i.idBarang}}</th>
                <td>{{i.namaBarang}}</td>
                <td>{{i.harga}}</td>
                <td>{{i.status}}</td>
                <td><div class="d-flex justify-content-center"> 
                <button class="btn btn-success"><a href="{% url 'barang:detailBarang' i.idBarang %}"
                  style="text-decoration: none; color: #FFFFFF;">Detail</a></button>
                {% if i.is_terjual == False %}
                <form action = "/transaksi/createTransaksi" method ="get">
                    <input type = "hidden" id="idBarang" name="idBarang" value="{{i.idBarang}}">
                    <button type="submit" class="btn btn-danger">Beli</button>
                </form>
              {% endif %}
            </div></td> 
          </tr>
          {% endfor %}
          {% endif %}
        </tbody>
      </table>
<br>
{% if request.user.is_penjual == True %}
<div class="d-flex justify-content-center">
  <button type="submit" class="btn btn-success"><a href="/barang/createBarang/"
      style="text-decoration: none; color: #FFFFFF;">Buat Barang Baru</a></button>
</div>
{% endif %}
{% endblock content %}

barang/templates/updateBarang.html
{% extends 'base.html' %}
{% block content %}

<h3 style="text-align: center;">FORM UPDATE BARANG</h3>
<br>

<div class="container">
    <form method="post">
        {% if msg %}
                {{ msg | safe }}
            {% endif %}
        {% csrf_token %}
        <div class="form-group">
            <label for="formGroupExampleInput">ID Barang:</label>
            {{form.idBarang}}
          </div>
        <div class="form-group">
            <label for="formGroupExampleInput">Nama Barang:</label>
            {{form.namaBarang}}
          </div>
          <div class="form-group">
            <label for="formGroupExampleInput">Jenis Barang:</label>
            {{form.jenisBarang}}
          </div>
          <div class="form-group">
            <label for="formGroupExampleInput">Harga:</label>
            {{form.harga}}
          </div>
        <div class="form-group">
            <label for="formGroupExampleInput">Status:</label>
            {{form.status}}
        </div>
        <div class="form-group">
            <label for="formGroupExampleInput">Ukuran:</label>
            {{form.ukuran}}
        </div>
        <div class="form-group">
            <label for="formGroupExampleInput">Kondisi:</label>
            {{form.kondisi}}
        </div>
          <span class="text-error">{{ form.errors }}</span>
        <div class="d-flex justify-content-center">
            <input type="submit"  value="Update" class="btn btn-pill text-white btn-block btn-primary">
            <a class = "btn btn-danger" href="/barang/listBarang">Batal</a>
        </div>
    </form>
</div>

{% endblock content %}