barang/urls.py
from django.urls import path
from . import views
app_name = 'barang'

urlpatterns = [
    path('listBarang/', views.readBarang, name ='readBarang'),
    path('createBarang/', views.createBarang, name = 'createBarang'),
    path('updateBarang/<int:pk>', views.updateBarang, name = 'updateBarang'),
    path('detailBarang/<int:pk>/', views.detailBarang, name = 'detailBarang'),
    path('deleteBarang/', views.deleteBarang, name = 'deleteBarang'),
]

thrift_shop/urls.py
from django.contrib import admin
from django.urls import include, path, re_path
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('authentication.urls')),
    path('barang/', include('barang.urls')),
    path('transaksi/', include('transaksi.urls')),
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

transaksi/urls.py
from django.urls import path
from . import views
app_name = 'transaksi'

urlpatterns = [
    path('createTransaksi/', views.createTransaksi, name='createTransaksi'),
    path('listTransaksi/', views.readTransaksi, name = 'readTransaksi'),
]

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet"
    integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"
    integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous">
  </script>
  <link rel="stylesheet" href="{% static 'style.css' %}">
  {% block meta %}
  {% endblock meta %}
</head>

<body>
  <div id="root">
    {% include 'navbar.html' %}

    <main>

      <div class="container">
        {% block content %}
        {% endblock content %}
      </div>
    </main>
  </div>
  <!-- Optional JavaScript -->
  <!-- jQuery first, then Popper.js, then Bootstrap JS -->
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js" ></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js"
    integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous">
  </script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"
    integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous">
  </script>
  <script src="https://cdn.jsdelivr.net/npm/@reliutg/buzz-notify/index.min.js"></script>
  <script src="{% static 'js/script.js' %}"></script>

  {% block js %}
  {% endblock js %}
</body>

</html>

templates/navbar.html
{% load static %}
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css"
    integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">

<!-- Optional JavaScript -->
<!-- jQuery first, then Popper.js, then Bootstrap JS -->

<nav class="navbar navbar-expand-lg navbar-light bg-light">
    <div class="container-fluid">
        <div class="navbar-header">
            {% if user.is_authenticated %}
            <a class="navbar-brand" href="/home/">Orange Thrift Shop</a>
            {% else %}
            <a class="navbar-brand" href="/">Orange Thrift Shop</a>
            {% endif %}
        </div>
        <div class="collapse navbar-collapse" id="navbarNav">
            <ul class="navbar-nav">
            {% if request.session.role == 'penjual'%}
            <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" data-toggle="dropdown"
                    aria-haspopup="true" aria-expanded="false">
                    Toko
                </a>
                <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
                    <a class="dropdown-item" href="{% url 'barang:readBarang' %}">List Barang Toko</a>
                </div>
            </li>
            {% endif %}
            {% if request.session.role == 'pembeli'%}
            <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" data-toggle="dropdown"
                    aria-haspopup="true" aria-expanded="false">
                    Barang
                </a>
                <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
                    <a class="dropdown-item" href="{% url 'barang:readBarang' %}">List Barang</a>
                    <a class="dropdown-item" href="{% url 'transaksi:readTransaksi' %}">List Barang Dibeli</a>
                </div>
            </li>
            {% endif %}
            </ul>
        </div>
        {% if user.is_authenticated %}
        <ul class="nav navbar-nav navbar-right">
            <a href="/logout/"><button type="button">LOG OUT</button></a>
        </ul>
        {% else %}
        <ul class="nav navbar-nav navbar-right">
            <a href="/login/"><button type="button">LOG IN</button></a>
            <a href="/register/"><button type="button">REGISTER</button></a>
        </ul>
        {% endif %}
    </div>
</nav>